[package]
name = "ethersync"
description = "Enables real-time co-editing of local text files."
version = "0.2.0"
edition = "2021"
default-run = "ethersync"

[dependencies]
serde_json = { version = "1" }
jsonrpc-core = "18.0.0"
clap = { version = "4.5.3", features = ["derive"] }
automerge = "0.5.9"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
operational-transform = "0.6.1"
anyhow = "1.0.81"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["local-time"] }
nvim-rs = { version = "0.7.0", features = ["use_tokio"] }
temp-dir = "0.1.13"
async-trait = "0.1.79"
pretty_assertions = "1.4.0"
futures = "0.3.30"
ropey = "1.6.1"
serde = "1.0.198"
tracing-test = "0.2.4"
time = { version = "0.3.36", features = ["formatting"] }
time-macros = { version = "0.2.0-alpha.1" }
local-ip-address = "0.6.1"
public-ip = "0.2.2"
tokio-util = "0.7.11"
ignore = "0.4.22"
notify = "6.1.1"
dissimilar = "1.0.9"
path-clean = "1.0.1"
libp2p = { version = "0.53.2", features = ["tokio", "quic"]}
libp2p-stream = "0.1.0-alpha.1"
libp2p-identity = { version ="0.2.9", features = ["ed25519"] }

[dev-dependencies]
assert_matches = "1.5"
serial_test = "3.1.1"
