name: Build & Test

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo fmt --check
  check_lua:
    name: Check Lua formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vim-plugin
    steps:
      - uses: actions/checkout@v4
      - run: cargo install stylua
      - run: stylua -c .
