name: Integration tests

on:
  push:
    branches:
      - 'main'
    paths:
      - 'daemon/**'
      - 'vim-plugin/**'
  pull_request:
    paths:
      - 'daemon/**'
      - 'vim-plugin/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./daemon
    steps:
        - uses: actions/checkout@v3
        - name: Install Nix
          uses: cachix/install-nix-action@v17
        - name: Run fuzzer
          run: nix develop --command cargo run --bin=fuzzer
