name: Rust Daemon

on:
  push:
    branches:
      - 'main'
    paths:
      - 'daemon/**'
  pull_request:
    paths:
      - 'daemon/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./daemon
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - run: cargo build --verbose
      - run: cargo test --verbose
  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./daemon
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
