name: Rust Daemon

on:
  push:
    branches:
      - 'main'
    paths:
      - 'daemon/**'
  pull_request:
    paths:
      - 'daemon/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./daemon
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - run: nix develop --command cargo build --verbose
      - name: Run unit tests
        run: nix develop --command cargo test --verbose --ignored
  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./daemon
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
