name: Rust

on:
  push:
    branches:
      - 'main'
    paths:
      - 'rust/**'
  pull_request:
    paths:
      - 'rust/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --verbose
      - run: cargo test --verbose
  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check
