name: Vim plugin

on:
  push:
    branches:
      - 'main'
    paths:
      - 'vim-plugin/**'
  pull_request:
    paths:
      - 'vim-plugin/**'

jobs:
  check_lua:
    name: Check Lua formatting and linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vim-plugin
    steps:
      - uses: actions/checkout@v4
      - run: cargo install stylua
      - name: Stylua Formatting
        run: stylua -c .
      - name: Luacheck Linting
        uses: lunarmodules/luacheck@v1
        with:
          args: --config vim-plugin/.luacheckrc vim-plugin
